### ISSUE TITLE
Failed to call removeLast() in TreadLine Component

### ISSUE THREAD

**Issue by li-huo** [rrag/react-stockcharts#201]
Hi there, 
I reuse the following code to capture the user keyboard press. 
```
switch (keyCode) {
	      case 46: { // DEL
			 console.log(this.refs.trend);
		         this.refs.trend.removeLast();
}
```
where TreadLine is defined as 
```
<TrendLine ref="trend" id={2}
				forChart={2}
				enabled={this.state.enableTrendLine}
				type="LINE"
				snap={true} snapTo={d => [d.high, d.low]}
				onStart={() => console.log("START")}
				onComplete={this.onTrendLineComplete}/>
```
When pressing DEL, it returns error - "removeLast is not a function"
I try to console log the object of this.refs.trend and it looks like this. 
![image](https://cloud.githubusercontent.com/assets/17079439/21566905/a4d3f048-cee2-11e6-8788-5dd02e92ae4f.png)

I was using ver 0.5 not sure that is the root cause.

In version 0.6 it works fine and the same log returns 
![image](https://cloud.githubusercontent.com/assets/17079439/21566926/ddc510b2-cee2-11e6-90ab-bae3a830d2e4.png)

Thanks in advance

**Comment by rrag** [comment]
it works in 0.6 right? I am not sure what the problem was in 0.5.

If you have problems in 0.6 I can look to fix it.

**Comment by li-huo** [comment]
I looked into the source code of TreadLine.js in 0.5. Functions like 'removeLast' or 'terminate' are defined as following. Is this the reason why I call " this.refs.trend.removeLast()" removelast cannot be referred? I am not familiar with this definition. Can you help explain?

![image](https://cloud.githubusercontent.com/assets/17079439/21577900/0b732e6c-cfa7-11e6-83b9-7efe3dc893a5.png)

**Comment by rrag** [comment]
This is the output of babel.

**Comment by li-huo** [comment]
thanks @rrag,   it turns out the methods are called through a wrapped component. The following works
```
this.refs.trend.getWrappedComponent().removeLast();
```
